name: Deploy to EC2

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # SSH into EC2 and deploy
            - name: SSH into EC2 and deploy
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      # Navigate to the project directory
                      cd /path/to/your/repos
                      
                      # Pull the latest changes from the master branch
                      git pull origin master
                      
                      # Build the Docker image
                      docker build -t snapshare .
                      
                      # Stop and remove the existing container (if it exists)
                      docker stop snapshare_container || true
                      docker rm snapshare_container || true
                      
                      # Run the new container
                      docker run -d -p 8000:8000 --name snapshare_container snapshare


